version: '3.9'

services:
  app:
    build: .
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"  # This is the fix: publish container port to host
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
